import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ReactNode} from "react";
import { ThemeProvider } from "@/components/ui/theme-provider"
import {Toaster} from "@/components/ui/toaster";

const SpaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk.woff",
  variable: "--font-space-grotesk",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {

  return (
      <html lang="en">
        <body
            className={`${SpaceGrotesk.className} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
            {children}
            <Toaster />
        </ThemeProvider>
        </body>
      </html>
  );
}

export default RootLayout;
